"""Add Auth and RAG models

Revision ID: 2b0aa03c1a5c
Revises: 
Create Date: 2026-01-16 19:46:52.459096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b0aa03c1a5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_tokens_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('idx_zone_object_id', table_name='zone_events')
    op.drop_index('idx_zone_time', table_name='zone_events')
    op.drop_index('idx_zone_upload_id', table_name='zone_events')
    op.drop_index('idx_zone_zone_id', table_name='zone_events')
    op.drop_table('zone_events')
    op.drop_index('ix_videos_video_id', table_name='videos')
    op.drop_table('videos')
    op.drop_index('idx_ppe_severity', table_name='ppe_violations')
    op.drop_index('idx_ppe_time', table_name='ppe_violations')
    op.drop_index('idx_ppe_track_id', table_name='ppe_violations')
    op.drop_table('ppe_violations')
    op.add_column('document_vectors', sa.Column('upload_id', sa.UUID(), nullable=False))
    op.add_column('document_vectors', sa.Column('chunk_text', sa.Text(), nullable=False))
    op.add_column('document_vectors', sa.Column('metadata', sa.JSON(), nullable=True))
    op.add_column('document_vectors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('idx_document_vectors_chunk', table_name='document_vectors')
    op.drop_index('idx_document_vectors_document', table_name='document_vectors')
    op.drop_index('ix_document_vectors_chunk_id', table_name='document_vectors')
    op.drop_index('ix_document_vectors_document_id', table_name='document_vectors')
    # FIX: Casting embedding to vector(384) for ivfflat index
    op.execute("ALTER TABLE document_vectors ALTER COLUMN embedding TYPE vector(384)")
    op.create_index('idx_doc_vectors_embedding', 'document_vectors', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index(op.f('ix_document_vectors_upload_id'), 'document_vectors', ['upload_id'], unique=False)
    op.drop_column('document_vectors', 'document_id')
    op.drop_column('document_vectors', 'content')
    op.drop_column('document_vectors', 'chunk_index')
    op.drop_column('document_vectors', 'extra_metadata')
    op.drop_column('document_vectors', 'chunk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_vectors', sa.Column('chunk_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('document_vectors', sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('document_vectors', sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('document_vectors', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('document_vectors', sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_document_vectors_upload_id'), table_name='document_vectors')
    op.drop_index('idx_doc_vectors_embedding', table_name='document_vectors', postgresql_using='ivfflat')
    op.create_index('ix_document_vectors_document_id', 'document_vectors', ['document_id'], unique=False)
    op.create_index('ix_document_vectors_chunk_id', 'document_vectors', ['chunk_id'], unique=False)
    op.create_index('idx_document_vectors_document', 'document_vectors', ['document_id'], unique=False)
    op.create_index('idx_document_vectors_chunk', 'document_vectors', ['chunk_id'], unique=False)
    op.drop_column('document_vectors', 'created_at')
    op.drop_column('document_vectors', 'metadata')
    op.drop_column('document_vectors', 'chunk_text')
    op.drop_column('document_vectors', 'upload_id')
    op.create_table('ppe_violations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('violation_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('missing_items', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("severity = ANY (ARRAY['LOW'::text, 'MEDIUM'::text, 'HIGH'::text])", name='ppe_violations_severity_check'),
    sa.CheckConstraint("violation_type = 'PPE'::text", name='ppe_violations_violation_type_check'),
    sa.CheckConstraint('confidence >= 0::double precision AND confidence <= 1::double precision', name='ppe_violations_confidence_check'),
    sa.PrimaryKeyConstraint('id', name='ppe_violations_pkey')
    )
    op.create_index('idx_ppe_track_id', 'ppe_violations', ['track_id'], unique=False)
    op.create_index('idx_ppe_time', 'ppe_violations', ['start_time', 'end_time'], unique=False)
    op.create_index('idx_ppe_severity', 'ppe_violations', ['severity'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_frames', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processed_frames', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='videos_pkey')
    )
    op.create_index('ix_videos_video_id', 'videos', ['video_id'], unique=False)
    op.create_table('zone_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('object_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('zone_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='zone_events_pkey')
    )
    op.create_index('idx_zone_zone_id', 'zone_events', ['zone_id'], unique=False)
    op.create_index('idx_zone_upload_id', 'zone_events', ['upload_id'], unique=False)
    op.create_index('idx_zone_time', 'zone_events', ['event_time'], unique=False)
    op.create_index('idx_zone_object_id', 'zone_events', ['object_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_family', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
